# docker-compose.yml
services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: bundle_dev_php
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    working_dir: /app/tests/sandbox
    command: php -S 0.0.0.0:8000 -t public